# Generated by Django 5.0.4 on 2024-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ststic_text', models.CharField(max_length=50, verbose_name='HomeInfo')),
                ('dinamic_text1', models.CharField(max_length=50, verbose_name='HomeInfo text 1')),
                ('dinamic_text2', models.CharField(max_length=50, verbose_name='HomeInfo text 2')),
                ('dinamic_text3', models.CharField(max_length=50, verbose_name='HomeInfo text 3')),
                ('about', models.TextField(verbose_name='HomeInfo')),
                ('button_name', models.CharField(max_length=50, verbose_name='HomeInfo')),
            ],
        ),
    ]
