# Generated by Django 5.0.4 on 2024-05-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeinfo',
            old_name='ststic_text',
            new_name='static_text',
        ),
    ]
