# Generated by Django 5.0.4 on 2024-05-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_ststic_text_homeinfo_static_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=50, verbose_name='IntroPage')),
                ('main_text', models.TextField(verbose_name='IntroPage')),
                ('other_text', models.TextField(verbose_name='IntroPage')),
            ],
        ),
    ]
