# Generated by Django 5.0.4 on 2024-05-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=50, verbose_name='Explain')),
                ('text2', models.TextField(verbose_name='Explain')),
                ('text3', models.CharField(max_length=50, verbose_name='Explain')),
                ('text4', models.TextField(verbose_name='Explain')),
                ('text5', models.CharField(max_length=50, verbose_name='Explain')),
                ('text6', models.TextField(verbose_name='Explain')),
            ],
        ),
    ]
