# Generated by Django 5.0.4 on 2024-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_explain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img2', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img3', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img4', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img5', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img6', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img7', models.ImageField(upload_to='media', verbose_name='Image')),
                ('img8', models.ImageField(upload_to='media', verbose_name='Image')),
            ],
        ),
    ]
