# Generated by Django 5.0.4 on 2024-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='img',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='IntroPage'),
        ),
    ]
