# Generated by Django 5.0.4 on 2024-05-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_intro_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='img',
            field=models.ImageField(blank=True, upload_to='intro', verbose_name='IntroPage'),
        ),
    ]
