# Generated by Django 5.0.4 on 2024-05-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_picture_img1_alter_picture_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project', verbose_name='Project')),
                ('name1', models.CharField(max_length=50, verbose_name='Project name')),
                ('name2', models.CharField(max_length=50, verbose_name='Project name2')),
                ('text1', models.TextField(verbose_name='Project text1')),
                ('text2', models.TextField(verbose_name='Project text1')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
