# Generated by Django 5.0.4 on 2024-05-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone1', models.CharField(max_length=50, verbose_name='Phone1')),
                ('phone2', models.CharField(max_length=50, verbose_name='Phone2')),
                ('mail', models.EmailField(max_length=254, verbose_name='Email')),
                ('fb', models.TextField(verbose_name='Facebook')),
                ('insta', models.TextField(verbose_name='Instagram')),
            ],
        ),
    ]
